### ISSUE TITLE
post install requirements

### ISSUE THREAD

**Issue by BustedSec** [droope/droopescan#13]
after installing I had to run 
easy_install cement
and 
easy_install pystache

**Comment by diego-treitos** [comment]
adding to post install requirements: `/usr/local/bin/droopescan` does not have execution permissions after installing with `pip`

**Comment by droope** [comment]
hi @diego-treitos, what version of linux are you using? I had similar issues with debian testing, I'll look into it when I have some time

**Comment by droope** [comment]
Hi @BustedSec , how did you install droopescan? Was it by a regular pip install? 

Those requirements are in the current setup.py, but I am guessing that they didn't install for you for some unknown reason.

**Comment by droope** [comment]
Hey, closing pending more information, lemme know if you guys manage to reproduce again.
