### ISSUE TITLE
unable to detect exact version

### ISSUE THREAD

**Issue by blshkv** [droope/droopescan#15]
I've got the following output:
```
[+] Possible interesting urls found:
    Default changelog file - https://www.xxx.com/CHANGELOG.txt
    Default admin - https://www.xxx.com/user/login

[+] Possible version(s):
    7.51
    7.52
```
However, the first line of the CHANGELOG.txt clearly indicate:
```
Drupal 7.53, 2016-12-07
```

Please fix the tool

**Comment by droope** [comment]
Hi there,

The tool uses CHANGELOG.txt to aid in fingerprinting, but in certain cases ignores that data in order to prevent false positives. 

If you can provide a run with `--debug-requests` that would help me reproduce the issue, I am happy to resolve it if you provide enough information.

**Comment by blshkv** [comment]
Hi, my test server has been removed unfortunately, I'm unable to verify it.
But I'm sure it's a trivial task and you have tested against any other server (https://www.drupal.org/CHANGELOG.txt)

**Comment by droope** [comment]
Yeap works against drupal.org, it was due to the versions.xml file being out of date but its fixed now.
