### ISSUE TITLE
unable to detect Drupal plugins

### ISSUE THREAD

**Issue by blshkv** [droope/droopescan#16]
I'm using the latest git (409f9ba3f101fa2e84caecaa1ddf6f693e52399c) and the output of the tool is below:
```
[+] No plugins found.
```

I have admin access to the Drupal CMS and there are about 100 modules installed and the following 4 (as an example) are not up to date:
```
Workbench Moderation 
GMap Module
Session Limit
Token
Workbench Access
```

**Comment by droope** [comment]
Hi there,

Can you provide either of the following?

* The URL for the site? Can be over email at pedro@worcel.com but I understand if you can't.
* A directory listing of sites/all/modules?
* The output of a droopescan run with `--debug-requests`?

Sorry about the late response.

**Comment by blshkv** [comment]
Hi, I have tried the latest version (a0f56b88fd4895c3de6b969fb89a9b2e27943e5b) and it detected 2 plugins:

```
[+] Plugins found:
    transliteration https://www.xxx.com/sites/all/modules/transliteration/
        https://www.xxx.com/sites/all/modules/transliteration/CHANGELOG.txt
        https://www.xxx.com/sites/all/modules/transliteration/README.txt
        https://www.xxx.com/sites/all/modules/transliteration/LICENSE.txt
    security_review https://www.xxx.com/sites/all/modules/security_review/
        https://www.xxx.com/sites/all/modules/security_review/README.txt
        https://www.xxx.com/sites/all/modules/security_review/LICENSE.txt
        https://www.xxx.com/sites/all/modules/security_review/API.txt

```
So I guess the issue is fixed. 

Sorry, I'm unable to provide more info as I don't have an admin access anymore.

**Comment by droope** [comment]
Hey

Thanks for closing the issue. Sometimes there are issues with detection, but hopefully that won't happen to you again. Next time if you can provide even a censored version of `--debug-requests` I'll have a look into it and see what's up.

Ta,
Pedro
