### ISSUE TITLE
Missing 'Site identified as *' in JSON output

### ISSUE THREAD

**Issue by thEpisode** [droope/droopescan#20]
Hi, I'm using JSON output to automate some tasks, but comparing results in JSON output can't show anywhere the flag '[+] Site identified as joomla.'. Thanks.

* URL for site: konradlorenz.edu.co
* OS & installation method: Ubuntu Server 16.04, pip and git clone
* Working command used:  ./droopescan scan -u konradlorenz.edu.co --debug-requests
* Not working command used: ./droopescan scan -u konradlorenz.edu.co --output json --debug-requests
* Working output of run with `--debug-requests`:

[head] http://konradlorenz.edu.co/ None 301
[+] Accepted redirect to http://www.konradlorenz.edu.co/
[get] http://www.konradlorenz.edu.co/wp-admin/wp-admin.css None 404
[get] http://www.konradlorenz.edu.co/wp-includes/js/tinymce/tiny_mce_popup.js None 404
[get] http://www.konradlorenz.edu.co/media/system/js/validate.js None 200 f5ae2571cc4ad48b8f24e7ce6fd83c55
[+] Site identified as joomla.
[head] http://www.konradlorenz.edu.co/joomla.xml None 200
[head] http://www.konradlorenz.edu.co/administrator/manifests/files/joomla.xml None 200
[head] http://www.konradlorenz.edu.co/administrator/ None 200
[head] http://www.konradlorenz.edu.co/libraries/simplepie/README.txt None 200
[head] http://www.konradlorenz.edu.co/LICENSE.txt None 200
[head] http://www.konradlorenz.edu.co/plugins/system/cache/cache.xml None 200
[get] http://www.konradlorenz.edu.co/media/system/js/validate.js None 200 f5ae2571cc4ad48b8f24e7ce6fd83c55
[get] http://www.konradlorenz.edu.co/templates/system/css/offline.css None 200 355d145a7f2c8acf0367824242438370
[get] http://www.konradlorenz.edu.co/media/system/css/calendar-jos.css None 200 e5b1530cc7c9a3cb5876538b203662e1
[get] http://www.konradlorenz.edu.co/templates/system/css/general.css None 200 44ecb423ff214ad8bfcf7b95f126f9c4
[get] http://www.konradlorenz.edu.co/templates/system/css/system.css None 200 edd0080470c6fc2b6656fb841d84a6c7
[get] http://www.konradlorenz.edu.co/templates/system/css/error.css None 200 7aaba0755cf8e7b864fbf61c61490f55
[get] http://www.konradlorenz.edu.co/media/system/js/tabs.js None 200 efd1b231a7270ee76424dc87dde87049
[+] Possible interesting urls found:
    This CMS' default changelog. - http://www.konradlorenz.edu.co/joomla.xml
    Detailed version information. - http://www.konradlorenz.edu.co/administrator/manifests/files/joomla.xml
    Login page. - http://www.konradlorenz.edu.co/administrator/
    SimplePie README. - http://www.konradlorenz.edu.co/libraries/simplepie/README.txt
    License file. - http://www.konradlorenz.edu.co/LICENSE.txt
    Version attribute contains approx version - http://www.konradlorenz.edu.co/plugins/system/cache/cache.xml

[+] Possible version(s):
    2.5.5
    2.5.6
    2.5.7
    2.5.8
    3.0.0
    3.0.1
    3.0.2

* Not working output of run with `--debug-requests`:

[head] http://konradlorenz.edu.co/ None 301
[get] http://www.konradlorenz.edu.co/wp-admin/wp-admin.css None 404
[get] http://www.konradlorenz.edu.co/wp-includes/js/tinymce/tiny_mce_popup.js None 404
[get] http://www.konradlorenz.edu.co/media/system/js/validate.js None 200 f5ae2571cc4ad48b8f24e7ce6fd83c55
[head] http://www.konradlorenz.edu.co/joomla.xml None 200
[head] http://www.konradlorenz.edu.co/administrator/manifests/files/joomla.xml None 200
[head] http://www.konradlorenz.edu.co/administrator/ None 200
[head] http://www.konradlorenz.edu.co/libraries/simplepie/README.txt None 200
[head] http://www.konradlorenz.edu.co/LICENSE.txt None 200
[head] http://www.konradlorenz.edu.co/plugins/system/cache/cache.xml None 200
[get] http://www.konradlorenz.edu.co/media/system/js/validate.js None 200 f5ae2571cc4ad48b8f24e7ce6fd83c55
[get] http://www.konradlorenz.edu.co/templates/system/css/offline.css None 200 355d145a7f2c8acf0367824242438370
[get] http://www.konradlorenz.edu.co/media/system/css/calendar-jos.css None 200 e5b1530cc7c9a3cb5876538b203662e1
[get] http://www.konradlorenz.edu.co/templates/system/css/general.css None 200 44ecb423ff214ad8bfcf7b95f126f9c4
[get] http://www.konradlorenz.edu.co/templates/system/css/system.css None 200 edd0080470c6fc2b6656fb841d84a6c7
[get] http://www.konradlorenz.edu.co/templates/system/css/error.css None 200 7aaba0755cf8e7b864fbf61c61490f55
[get] http://www.konradlorenz.edu.co/media/system/js/tabs.js None 200 efd1b231a7270ee76424dc87dde87049
{"interesting urls": {"is_empty": false, "finds": [{"url": "http://www.konradlorenz.edu.co/joomla.xml", "description": "This CMS' default changelog."}, {"url": "http://www.konradlorenz.edu.co/administrator/manifests/files/joomla.xml", "description": "Detailed version information."}, {"url": "http://www.konradlorenz.edu.co/administrator/", "description": "Login page."}, {"url": "http://www.konradlorenz.edu.co/libraries/simplepie/README.txt", "description": "SimplePie README."}, {"url": "http://www.konradlorenz.edu.co/LICENSE.txt", "description": "License file."}, {"url": "http://www.konradlorenz.edu.co/plugins/system/cache/cache.xml", "description": "Version attribute contains approx version"}]}, "version": {"is_empty": false, "finds": ["2.5.5", "2.5.6", "2.5.7", "2.5.8", "3.0.0", "3.0.1", "3.0.2"]}}
* Expected result: {CMS:"Joomla", ...}

**Comment by droope** [comment]
Hi, I will look into this

**Comment by droope** [comment]
Hi, I can verify your results, and I will implement a fix. In the meantime, you can use the following as a workaround, writing to a file and using the url file parameter.

<pre>
[root@debian-dev droopescan (development)]# echo site.edu.co > /tmp/a
[root@debian-dev droopescan (development)]# ./droopescan scan -U /tmp/a --output json -e v
{"host": "('http://www.site.edu.co/', None)", "version": {"is_empty": false, "finds": ["2.5.5", "2.5.6", "2.5.7", "2.5.8", "3.0.0", "3.0.1", "3.0.2"]}, "cms_name": "joomla"}
</pre>

**Comment by droope** [comment]
I've created and uploaded version 1.38.0 which resolves this issue. You can upgrade with `pip install -U droopescan`

**Comment by thEpisode** [comment]
Thank you so much, I will try in a few hours 😄

**Comment by thEpisode** [comment]
I can't wait jaja 😆 I tried with different CMS and works perfect
