### ISSUE TITLE
Typo3 support

### ISSUE THREAD

**Issue by gottburgm** [droope/droopescan#30]
Hello,

Are you interested into adding TYPO3 CMS support ? we can work together on it, already implemented it in my own tool in Perl so i have most of the basics stuff

**Comment by droope** [comment]
Hi!

I am definitely willing to accept a PR for Typo3, the main requirement would be for the automatic version updating to be implemented, using the update_version_check, update_version, update_plugins_check and update_plugins functions. There's some more info here, although docs are not 100% at the moment: update_version_check, update_version, update_plugins_check and update_plugins

**Comment by gottburgm** [comment]
As soon as i got more time i will take a look more deeper into the code and keep you aware by writting here ! :)

**Comment by droope** [comment]
Temporarilly closing this one, feel free to reopen or push a PR. I may have some free time to improve droopescan soon but I think I will be looking into wordpress which has some teething issues.
