### ISSUE TITLE
[feature] User agent swap

### ISSUE THREAD

**Issue by elogada** [droope/droopescan#40]
Hey @droope 

Either there's no way to change my `User-agent` header, or I can't find it in the help docs. Any way you can add a functionality that allows me to change the `User-agent` of a scan?

Thanks!

**Comment by droope** [comment]
Hi there,

I'd be willing to accept a PR for this change provided it comes with a unit test. The change would have to occur on [this line](https://github.com/droope/droopescan/blob/424c48a0f9d12b4536dbef5a786f0fbd4ce9519a/dscan/plugins/internal/base_plugin_internal.py#L268).

Alternatively you can clone the repository and manually modify the DEFAULT_UA variable for your purposes.

Thanks!
Pedro

**Comment by droope** [comment]
Just so anybody who needs this knows, @kieran-github has implemented this feature into the development branch.

I will give it a test when I can and merge it into master, as well as release it into PyPi.
