### ISSUE TITLE
Droopescan can't find cement dependency unless ran with python3

### ISSUE THREAD

**Issue by pr0b3r7** [droope/droopescan#51]
root@kali$:./droopescan scan --help                                                  11:05:57
Traceback (most recent call last):
  File "./droopescan", line 3, in <module>
    from dscan import droopescan
  File "/opt/droopescan/dscan/droopescan.py", line 4, in <module>
    from cement.core import backend, foundation, controller, handler
ImportError: No module named cement.core

![image](https://user-images.githubusercontent.com/14915771/113589873-e9676a80-95ff-11eb-99c2-5fb6a23b7f27.png)

root@kali /opt/droopescan master* ❯ python ./droopescan scan --help                                                 11:07:31
Traceback (most recent call last):
  File "./droopescan", line 3, in <module>
    from dscan import droopescan
  File "/opt/droopescan/dscan/droopescan.py", line 4, in <module>
    from cement.core import backend, foundation, controller, handler
ImportError: No module named cement.core
root@kali /opt/droopescan master* ❯ python ./droopescan scan --help --debug-requests                                11:13:40
Traceback (most recent call last):
  File "./droopescan", line 3, in <module>
    from dscan import droopescan
  File "/opt/droopescan/dscan/droopescan.py", line 4, in <module>
    from cement.core import backend, foundation, controller, handler
ImportError: No module named cement.core

Linux kali 5.10.0-kali6-amd64 #1 SMP Debian 5.10.26-1kali2 (2021-04-01) x86_64 GNU/Linux

install method pip

However, when running with python3 and renaming the script to .py - it works. 

![image](https://user-images.githubusercontent.com/14915771/113590340-86c29e80-9600-11eb-871b-8b3e92eff760.png)

Thank you,
Robert

**Comment by droope** [comment]
Hi Robert,

Sorry for taking a little while in getting back to you on this one. It is a little bit mysterious because it seems to install properly but then it seems that it's not found.

I generally run my unit tests with Python 2 and 3, but haven't done a fresh install of droopescan in a while. I wonder if it is related to the deprecation of Python 2. I am unsure whether there are a lot of people still using Python 2 out there and if to continue supporting it. What do you think about this?

Is Kali still on Python 2?

Thanks,
Pedro

**Comment by NorthShad0w** [comment]
kali use command _python3_ to execute python version 3 script.
And use command _python_ to execute python version 2 script.
For kali user:
just edit first line in droopescan from **#!/usr/bin/env python** to **#!/usr/env/python3**

**Comment by droope** [comment]
Hmm. I feel like this will be a breaking change in the sense that it will break support with Python 2 users.

But Kali is one of the biggest users of droopescan. I'll have a think.

**Comment by droope** [comment]
Hi @NorthShad0w @pr0b3r7 

I released a new version which solves this.

Can you please confirm the fix? You can update by running `pip install -U droopescan`

**Comment by droope** [comment]
I'm going to reopen the issue until you have confirmed the fix. I'm concerned that I may have introduced issues with this change, but I can't see any problems on my end.

**Comment by NorthShad0w** [comment]
It works fine in my computer.

**Comment by droope** [comment]
Sweet, thank you! I appreciate it.
