### ISSUE TITLE
Add Specific Header in request

### ISSUE THREAD

**Issue by Tzion0** [droope/droopescan#53]
Hi, may i know how i add specific header in all the request? Example:
```Authorization: xxxx```

**Comment by droope** [comment]
Hi.

The best way to do this currently is to configure an upstream proxy as [documented here](https://github.com/droope/droopescan/#authentication). You could then use mitmproxy for example and create a custom addon that does this like [http-add-header.py](https://docs.mitmproxy.org/stable/addons-examples/#http-add-header).

All requests issued by droopescan are issued from a single `Session` object defined [here](https://github.com/droope/droopescan/blob/4b3f02f4a17f251698cd655d4beb8a120dd0fbce/dscan/plugins/internal/base_plugin_internal.py#L238). If many people need this feature and you are willing to implement it alongside some tests, I'd be happy to accept a PR for it.

Thanks.

**Comment by Tzion0** [comment]
Sorry, i wish i could help, but i'm not that good in coding. Besides, may i know the detail steps of configure the upstream proxy? I don't understand the documentation... Thank you in advance

**Comment by droope** [comment]
Hi there,

Basically you:

1. Configure droopescan to use a proxy using http_proxy variables. More info [here](https://www.putorius.net/how-to-set-httpproxy-variable-in-linux.html#:~:text=The%20http_proxy%20variable%20tells%20the,to%20update%20you%20Linux%20system).).
2. Configure burp to add the required header

Let me know if this works for you, or what particular step you need help with.

Thanks!
Pedro

**Comment by Tzion0** [comment]
Hi, i do exactly the same step but this time worked! Thank you !
