### ISSUE TITLE
Update for Drupal 9?

### ISSUE THREAD

**Issue by greggmarshall** [droope/droopescan#54]
This has been a fun project to discover.

It would appear the latest version of Drupal 9 that was fingerprinted is 9.2.0-rc1, even though "droopescan stats" only shows 9.2.0-beta3.  Since then 9.2.0, 9.2.1 and 9.2.2 have been released.  I presume there are additional releases in the other Drupal branches given 9.2.2 was a security release.

Any timescale on when an update to support them might be out?

**Comment by droope** [comment]
Hi

I won’t be able to do this in the next couple of days. The update mechanism
in droopescan however can be used by anyone and if it’s urgent you can run
it

./droopescan update —help

This will clone drupal and attempt to extract the hashes. Let me know what
you think

**Comment by greggmarshall** [comment]
Thanks for that hint.

What came for help was a bit confusing, so I tried a simple droopescan update to see what would happen.  I almost immediately got a "NameError: name 'BeautifulSoup' is not defined" error.  Not having time, I haven't really looked into it.

**Comment by droope** [comment]
Yeah it’s only meant to be run by maintainers. You need to install the dev
dependencies:

pip install -r requirements_test.txt

lmk how that goes

**Comment by droope** [comment]
Hi

I have released version 1.45.1 that resolves this issue. 

Thank you for the heads up!

**Comment by greggmarshall** [comment]
Thank you!
