### ISSUE TITLE
drupal module detection

### ISSUE THREAD

**Issue by adewinne** [droope/droopescan#9]
I've scanned 4 drupal sites, and out of all four there has only been one hit of modules (features). Is that the expected output, or should I be seeing many more module hits?

**Comment by droope** [comment]
Hi adewinne,

It's hard to say without knowing what is installed on the sites. I understand that it would be hard to publish the URLs of the sites you are testing, but you could perhaps retry with `--debug-requests`. This will give you a detailed output of each request droopescan is doing, and you can see if there are clear modules there which droopescan is missing. 

Normally, I would expect other modules to be installed as well (cck and views are very common, for example.) 

Let me know how it goes. I will be offline this weekend, but will reply to your queries first thing after.

Ta,
Pedro

**Comment by droope** [comment]
Hey @adewinne,

I imagine you've gotten this sorted now, I'll close the issue. If you still have issues please feel free to reopen it.

Ta,
Pedro
